title: Title
description: Personal webpage of Vasileios Papapanagiotou
theme: just-the-docs

url: https://vpapapanagiotou.github.io/name

aux_links:
  Template Repository: https://github.com/vpapapanagiotou/name2
